version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  backend:
    build: .
    container_name: olimpiadas-escolares
    environment:
      DATABASE_NAME: 'db'
      DATABASE_USER: 'user'
      DATABASE_PASSWORD: 'password'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '3306'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src
    links:
      - db
    depends_on:
      - db
    restart: always
    command: npm run dev

volumes:
  db:
    driver: local
